server:
  # 设置端口号Environment
  port: 8082
  # path前缀
  servlet.context-path: /api
  # 编码格式
  tomcat.uri-encoding: UTF-8

# 日志采用debug模式
debug: true

# 声明注册其他配置文件
spring:
  profiles:
    active: service,dao