server:
  # 设置端口号Environment
  port: 8082
  # path前缀
  # servlet.context-path: /api
  # 编码格式
  tomcat.uri-encoding: UTF-8
  servlet:
    jsp:
      init-parameters:
        # 更改jsp或者js后立即刷新
        development: true

# 日志采用debug模式
debug: true

spring:
  # 声明注册其他配置文件,多个用逗号分隔
  profiles:
    active: service,dao

  # 使用thymeleaf模板引擎
  thymeleaf:
    enabled: true # 默认启用
    cache: false # 禁用缓存，否则热部署不生效
    prefix: classpath:templates/
    surfix: .html
    context-type: text/html
    mode: HTML5
    encoding: UTF-8

  # 静态资源访问
  mvc:
    static-path-pattern: /static/**

  # 使用jsp， 使用spring-boot:run启动， 不可以直接运行main方法启动
#  mvc:
#    static-path-pattern: /static/**
#    view:
#      suffix: .jsp
#      prefix: /WEB-INF/jsp/
#  thymeleaf:
#    enabled: false
#    cache: false